import type { SiteConfig } from '~/types'

const config: SiteConfig = {
  site: 'https://anmolsharma152.github.io',
  title: 'Anmol Sharma',
  description:
    'Agentic AI & Systems Engineer. Building Low-Latency AI Infra & Stateful Multi-Agent Backends.',
  author: 'Anmol Sharma',
  tags: ['Agentic AI', 'Systems Engineering', 'LLMOps', 'Multi-Agent Systems', 'Python', 'FastAPI', 'IIT Mandi'],
  socialCardAvatarImage: './public/profile.jpg',
  font: 'JetBrains Mono Variable',
  pageSize: 6,
  trailingSlashes: false,
  navLinks: [
    { name: 'Home', url: '/' },
    { name: 'About', url: '/about' },
    { name: 'Projects', url: '/projects' },
    { name: 'Archive', url: '/posts' },
    { name: 'Resume', url: '/resume.pdf', external: true },
    {
      name: 'GitHub',
      url: 'https://github.com/anmolsharma152',
      external: true,
    },
  ],
  themes: {
    mode: 'select',
    default: 'github-dark-default',
    include: [
      'andromeeda',
      'aurora-x',
      'ayu-dark',
      'catppuccin-frappe',
      'catppuccin-latte',
      'catppuccin-macchiato',
      'catppuccin-mocha',
      'dark-plus',
      'dracula',
      'dracula-soft',
      'everforest-dark',
      'everforest-light',
      'github-dark',
      'github-dark-default',
      'github-dark-dimmed',
      'github-dark-high-contrast',
      'github-light',
      'github-light-default',
      'github-light-high-contrast',
      'gruvbox-dark-hard',
      'gruvbox-dark-medium',
      'gruvbox-dark-soft',
      'gruvbox-light-hard',
      'gruvbox-light-medium',
      'gruvbox-light-soft',
      'houston',
      'kanagawa-dragon',
      'kanagawa-lotus',
      'kanagawa-wave',
      'laserwave',
      'light-plus',
      'material-theme',
      'material-theme-darker',
      'material-theme-lighter',
      'material-theme-ocean',
      'material-theme-palenight',
      'min-dark',
      'min-light',
      'monokai',
      'night-owl',
      'nord',
      'one-dark-pro',
      'one-light',
      'plastic',
      'poimandres',
      'red',
      'rose-pine',
      'rose-pine-dawn',
      'rose-pine-moon',
      'slack-dark',
      'slack-ochin',
      'snazzy-light',
      'solarized-dark',
      'solarized-light',
      'synthwave-84',
      'tokyo-night',
      'vesper',
      'vitesse-black',
      'vitesse-dark',
      'vitesse-light',
    ],
    overrides: {},
  },
  socialLinks: {
    github: 'https://github.com/anmolsharma152',
    email: 'mailto:anmolsharma152.dev@gmail.com',
    linkedin: 'https://linkedin.com/in/anmolsharma152',
    rss: true,
  },
  giscus: undefined,
  characters: {},
}

export default config
